language: python
python: "3.6"
services: postgresql
before_script:
  - psql -c 'CREATE TABLE IF NOT EXISTS test_table (test_tableid SERIAL PRIMARY KEY, var_field VARCHAR, var_field2 VARCHAR, num_val INT);' -U postgres
  - psql -c '\dt' -U postgres
install:
  - pip install psycopg2
  - pip install mysqlclient
script: python -m unittest test_dbprime.py
