language: python
python: "3.6"
services: postgresql
before_install:
  - sudo apt-get install postgresql-server-dev-10.10
before_script:
  - psql -c 'CREATE DATABASE IF NOT EXISTS test_db (test_tableid SERIAL PRIMARY KEY, var_field VARCHAR, var_field2 VARCHAR, num_val INT);' -U postgres
install:
  - pip install psycopg2
script: test_dbprime.py
